In [ ]:
import json
from IPython.core.display import display, HTML
from google.colab import drive

import nltk
import re

from google.colab import data_table
import pandas as pd

In [ ]:
# wrap text to the viewing window for this notebook
def set_css(): display(HTML('''<style>pre {white-space: pre-wrap;}</style>'''))
get_ipython().events.register('pre_run_cell', set_css)

In [ ]:
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
!pip install openpyxl

In [ ]:
import openpyxl

In [ ]:
# Load the data
data_path = '/content/drive/MyDrive/QURAN_DF_Sample2.xlsx'
data = pd.read_excel(data_path)

data.head(5)

Index  Juz Num  Sura Num  Ayah Num  Sura Nam  \
0   5105       28        58         1  المجادلة   
1   5106       28        58         2  المجادلة   
2   5107       28        58         3  المجادلة   
3   5108       28        58         4  المجادلة   
4   5109       28        58         5  المجادلة   

                                           Ayah Text  \
0  قَدْ سَمِعَ اللَّهُ قَوْلَ الَّتِي تُجَادِلُكَ...   
1  الَّذِينَ يُظَاهِرُونَ مِنكُم مِّن نِّسَائِهِم...   
2  وَالَّذِينَ يُظَاهِرُونَ مِن نِّسَائِهِمْ ثُمّ...   
3  فَمَن لَّمْ يَجِدْ فَصِيَامُ شَهْرَيْنِ مُتَتَ...   
4  إِنَّ الَّذِينَ يُحَادُّونَ اللَّهَ وَرَسُولَه...   

                                          Clean Text  
0  قد سمع الله قول التي تجادلك في زوجها وتشتكي إل...  
1  الذين يظاهرون منكم من نسائهم ما هن أمهاتهم إن ...  
2  والذين يظاهرون من نسائهم ثم يعودون لما قالوا ف...  
3  فمن لم يجد فصيام شهرين متتابعين من قبل أن يتما...  
4  إن الذين يحادون الله ورسوله كبتوا كما كبت الذي...

In [ ]:
# Load the data
data_path = '/content/drive/MyDrive/Quran_df.xlsx'
data = pd.read_excel(data_path)

data.head(100)

Token    POS Tag     Location Sura Name
0      قد       CERT   T1A1S58J28  المجادلة
1     سمع          V   T2A1S58J28  المجادلة
2    الله         PN   T3A1S58J28  المجادلة
3     قول          N   T4A1S58J28  المجادلة
4    التي        REL   T5A1S58J28  المجادلة
..    ...        ...          ...       ...
95    كبت          V   T8A5S58J28  المجادلة
96  الذين        REL   T9A5S58J28  المجادلة
97     من          P  T10A5S58J28  المجادلة
98  قبلهم     N+PRON  T11A5S58J28  المجادلة
99    وقد  CONJ+CERT  T12A5S58J28  المجادلة

[100 rows x 4 columns]

In [ ]:
import pandas as pd

# Function to append sura codes to 'Location' based on 'Sura Name'
def append_sura_code(df):
    # Generate a dictionary to map 'Sura Name' to a unique code (if not provided)
    sura_to_code = {sura: idx + 1 for idx, sura in enumerate(df['Sura Name'].unique())}

    # Apply the mapping to 'Location'
    df['Location'] = df['Sura Name'].map(sura_to_code).astype(str).radd('N').radd(df['Location'])

    # Output the updated DataFrame and the mapping dictionary for reference
    print(df.head())
    print('\nSura Codes Dictionary:', sura_to_code)

# Call the function
append_sura_code(data)


  Token POS Tag      Location Sura Name
0    قد    CERT  T1A1S58J28N1  المجادلة
1   سمع       V  T2A1S58J28N1  المجادلة
2  الله      PN  T3A1S58J28N1  المجادلة
3   قول       N  T4A1S58J28N1  المجادلة
4  التي     REL  T5A1S58J28N1  المجادلة

Sura Codes Dictionary: {'المجادلة': 1, 'الحشر': 2, 'الممتحنة': 3, 'الصف': 4, 'الجمعة': 5, 'المنافقون': 6, 'التغابن': 7, 'الطلاق': 8, 'التحريم': 9, 'الملك': 10, 'القلم': 11, 'الحاقة': 12, 'المعارج': 13, 'نوح': 14, 'الجن': 15, 'المزمل': 16, 'المدثر': 17, 'القيامة': 18, 'الإنسان': 19, 'المرسلات': 20, 'النبأ': 21, 'النازعات': 22, 'عبس': 23, 'التكوير': 24, 'الانفطار': 25, 'المطففين': 26, 'الانشقاق': 27, 'البروج': 28, 'الطارق': 29, 'الأعلى': 30, 'الغاشية': 31, 'الفجر': 32, 'البلد': 33, 'الشمس': 34, 'الليل': 35, 'الضحى': 36, 'الشرح': 37, 'التين': 38, 'العلق': 39, 'القدر': 40, 'البينة': 41, 'الزلزلة': 42, 'العاديات': 43, 'القارعة': 44, 'التكاثر': 45, 'العصر': 46, 'الهمزة': 47, 'الفيل': 48, 'قريش': 49, 'الماعون': 50, 'الكوثر': 51, 'الكافرون': 52, 'النصر': 53

In [ ]:
# Save the updated DataFrame back to an Excel file
data.to_excel("/content/drive/MyDrive/updated_Quran_df.xlsx", index=False)

# Load the updated df
df = pd.read_excel('/content/drive/MyDrive/updated_Quran_df.xlsx')
df.head()

Token POS Tag      Location Sura Name
0    قد    CERT  T1A1S58J28N1  المجادلة
1   سمع       V  T2A1S58J28N1  المجادلة
2  الله      PN  T3A1S58J28N1  المجادلة
3   قول       N  T4A1S58J28N1  المجادلة
4  التي     REL  T5A1S58J28N1  المجادلة

In [ ]:
print("Unique Locations Sample:", df['Location'].unique()[:5])  # Check unique location formats

Unique Locations Sample: ['T1A1S58J28N1' 'T2A1S58J28N1' 'T3A1S58J28N1' 'T4A1S58J28N1'
 'T5A1S58J28N1']


In [ ]:
# Code 6
import pandas as pd
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
import numpy as np

tokenizer = Tokenizer()
tokenizer.fit_on_texts(df['Location'])
sequences = tokenizer.texts_to_sequences(df['Location'])

In [ ]:
# Create sequences (for use in training)
def create_train_sequences(locations):
    sequences = []
    for loc in locations:
        parts = [int(x) for x in re.split('T|A|S|J|N', loc) if x]
        sequences.append(parts)
    return sequences

sample_locations = df['Location'].tolist()
sample_sequences = create_train_sequences(sample_locations)

print(sample_locations[:5])
print(sample_sequences[:5])

['T1A1S58J28N1', 'T2A1S58J28N1', 'T3A1S58J28N1', 'T4A1S58J28N1', 'T5A1S58J28N1']
[[1, 1, 58, 28, 1], [2, 1, 58, 28, 1], [3, 1, 58, 28, 1], [4, 1, 58, 28, 1], [5, 1, 58, 28, 1]]


In [ ]:
# Prepare Data for Model
X = []
y = []
sequence_length = 5  # This can be adjusted based on the specific use-case

for i in range(len(sample_sequences) - sequence_length):
    X.append(sample_sequences[i:i+sequence_length])
    y.append(sample_sequences[i+sequence_length])

X = np.array(X)
y = np.array(y)

In [ ]:
print(X[:2])
print(y[:2])

[[[ 1  1 58 28  1]
  [ 2  1 58 28  1]
  [ 3  1 58 28  1]
  [ 4  1 58 28  1]
  [ 5  1 58 28  1]]

 [[ 2  1 58 28  1]
  [ 3  1 58 28  1]
  [ 4  1 58 28  1]
  [ 5  1 58 28  1]
  [ 6  1 58 28  1]]]
[[ 6  1 58 28  1]
 [ 7  1 58 28  1]]


In [ ]:
import numpy as np
from sklearn.model_selection import train_test_split

# Train-Test Split
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42)

# Reshape X for input into LSTM
X_train = X_train.reshape(X_train.shape[0], X_train.shape[1], 5)  # Adjusting the shape to (samples, time steps, features)
X_val = X_val.reshape(X_val.shape[0], X_val.shape[1], 5)

In [ ]:
print(X_train[:2])
print(y_train[:2])

[[[ 1  9 68 29 11]
  [ 2  9 68 29 11]
  [ 3  9 68 29 11]
  [ 4  9 68 29 11]
  [ 1 10 68 29 11]]

 [[ 1 15 84 30 27]
  [ 2 15 84 30 27]
  [ 3 15 84 30 27]
  [ 4 15 84 30 27]
  [ 5 15 84 30 27]]]
[[ 2 10 68 29 11]
 [ 6 15 84 30 27]]


In [ ]:
# Code 16
# Extract components and add as separate columns for easy access
df['Token_Number'] = df['Location'].apply(lambda x: int(x.split('T')[1].split('A')[0]))
df['Ayah_Number'] = df['Location'].apply(lambda x: int(x.split('A')[1].split('S')[0]))
df['Sura_Number'] = df['Location'].apply(lambda x: int(x.split('S')[1].split('J')[0]))
df['Juz_Number'] = df['Location'].apply(lambda x: int(x.split('J')[1].split('N')[0]))

# Initialize metadata dictionaries
metadata = {
    'max_tokens_per_ayah': {},
    'max_ayahs_per_sura': {},
    'ayah_ends_at': {},
    'juz_ends_at': {}
}

# Populate metadata dictionaries
for index, row in df.iterrows():
    sura, ayah, token, juz = row['Sura_Number'], row['Ayah_Number'], row['Token_Number'], row['Juz_Number']

    if sura not in metadata['max_tokens_per_ayah']:
        metadata['max_tokens_per_ayah'][sura] = {}
    if sura not in metadata['max_ayahs_per_sura']:
        metadata['max_ayahs_per_sura'][sura] = 0

    metadata['max_ayahs_per_sura'][sura] = max(metadata['max_ayahs_per_sura'][sura], ayah)
    metadata['max_tokens_per_ayah'][sura][ayah] = max(metadata['max_tokens_per_ayah'][sura].get(ayah, 0), token)
    metadata['ayah_ends_at'][(sura, ayah)] = token  # Last token of each Ayah

    # Check and update the last token of Juz
    if juz not in metadata['juz_ends_at']:
        metadata['juz_ends_at'][juz] = (sura, ayah, token)
    else:
        current_end = metadata['juz_ends_at'][juz]
        if (sura > current_end[0]) or \
           (sura == current_end[0] and ayah > current_end[1]) or \
           (sura == current_end[0] and ayah == current_end[1] and token > current_end[2]):
            metadata['juz_ends_at'][juz] = (sura, ayah, token)

print("Metadata prepared for prediction adjustments.")

Metadata prepared for prediction adjustments.


In [ ]:
print("Max Tokens per Ayah:", metadata['max_tokens_per_ayah'])

Max Tokens per Ayah: {58: {1: 18, 2: 23, 3: 21, 4: 26, 5: 18, 6: 15, 7: 47, 8: 38, 9: 20, 10: 17, 11: 31, 12: 23, 13: 24, 14: 19, 15: 10, 16: 10, 17: 15, 18: 17, 19: 15, 20: 8, 21: 9, 22: 51}, 59: {1: 11, 2: 41, 3: 14, 4: 12, 5: 13, 6: 25, 7: 37, 8: 18, 9: 31, 10: 23, 11: 28, 12: 16, 13: 12, 14: 23, 15: 11, 16: 17, 17: 10, 18: 18, 19: 10, 20: 10, 21: 18, 22: 13, 23: 19, 24: 17}, 60: {1: 49, 2: 13, 3: 13, 4: 52, 5: 13, 6: 19, 7: 15, 8: 21, 9: 21, 10: 56, 11: 21, 12: 39, 13: 20}, 61: {1: 11, 2: 9, 3: 9, 4: 11, 5: 24, 6: 32, 7: 16, 8: 11, 9: 14, 10: 12, 11: 15, 12: 17, 13: 9, 14: 36}, 62: {1: 12, 2: 21, 3: 8, 4: 10, 5: 23, 6: 18, 7: 9, 8: 18, 9: 22, 10: 15, 11: 21}, 63: {1: 17, 2: 12, 3: 11, 4: 22, 5: 14, 6: 18, 7: 20, 8: 17, 9: 18, 10: 21, 11: 11}, 64: {1: 17, 2: 11, 3: 9, 4: 14, 5: 13, 6: 16, 7: 18, 8: 10, 9: 27, 10: 11, 11: 16, 12: 11, 13: 9, 14: 19, 15: 8, 16: 16, 17: 12, 18: 5}, 65: {1: 42, 2: 30, 3: 21, 4: 28, 5: 14, 6: 32, 7: 25, 8: 14, 9: 7, 10: 17, 11: 34, 12: 25}, 66: {1: 15, 2:

In [ ]:
print("Max Ayahs per Sura:", metadata['max_ayahs_per_sura'])

Max Ayahs per Sura: {58: 22, 59: 24, 60: 13, 61: 14, 62: 11, 63: 11, 64: 18, 65: 12, 66: 12, 67: 30, 68: 52, 69: 52, 70: 44, 71: 28, 72: 28, 73: 20, 74: 56, 75: 40, 76: 31, 77: 50, 78: 40, 79: 46, 80: 42, 81: 29, 82: 19, 83: 36, 84: 25, 85: 22, 86: 17, 87: 19, 88: 26, 89: 30, 90: 20, 91: 15, 92: 21, 93: 11, 94: 8, 95: 8, 96: 19, 97: 5, 98: 8, 99: 8, 100: 11, 101: 11, 102: 8, 103: 3, 104: 9, 105: 5, 106: 4, 107: 7, 108: 3, 109: 6, 110: 3, 111: 5, 112: 4, 113: 5, 114: 6}


In [ ]:
import pandas as pd
import numpy as np
from collections import defaultdict
import random

# Step 1: Load the dataset
def load_data(file_path):
    return pd.read_excel(file_path)

# Step 2: Map Sura names to numerical IDs and create reverse map
def create_sura_id_map(df, sura_col='Sura Name'):
    sura_names = df[sura_col].unique()
    sura_name_to_id = {name: i+1 for i, name in enumerate(sura_names)}
    id_to_sura_name = {i+1: name for i, name in enumerate(sura_names)}
    return sura_name_to_id, id_to_sura_name

# Step 3: Update locations in the dataset
def update_location(row, sura_name_to_id):
    sura_id = sura_name_to_id.get(row['Sura Name'], 0)
    updated_location = f"{row['Location']}N{sura_id}"
    return updated_location

# Step 4: Prepare the dataset for the n-gram model
def prepare_ngram_data(df, n=3):
    # Create tuples of (sequence, next word, location of next word, sura of next word)
    data = []
    tokens = df['Token'].tolist()
    locations = df['Location'].tolist()
    suras = df['Sura Name'].tolist()
    for i in range(len(tokens)-n):
        sequence = tokens[i:i+n]
        next_word = tokens[i+n]
        next_location = locations[i+n]
        next_sura_id = df.loc[i+n, 'Sura ID']  # using Sura ID directly from the dataframe
        data.append((sequence, next_word, next_location, next_sura_id))
    return data

# Step 5: Train an n-gram model with location and sura
def train_ngram_model(data):
    model = defaultdict(lambda: [])
    for sequence, next_word, loc, sura_id in data:
        model[tuple(sequence)].append((next_word, loc, sura_id))
    return model

# Step 6: Prediction function with location and sura name output
def predict_next_word(model, input_sequence, id_to_sura_name):
    input_tuple = tuple(input_sequence[-3:])  # consider the last 3 tokens
    if input_tuple in model:
        predictions = model[input_tuple]
        chosen_prediction = random.choice(predictions)  # Randomly choose among the predictions
        next_word, location, sura_id = chosen_prediction
        sura_name = id_to_sura_name[sura_id]
        return next_word, location, sura_name
    else:
        return "Word not found", None, None

# Main execution
if __name__ == "__main__":
    # Load data
    quran_df = load_data('/content/drive/MyDrive/Quran_df.xlsx')

    # Create Sura ID map and reverse map
    sura_id_map, id_to_sura_name = create_sura_id_map(quran_df)

    # Update locations and add Sura ID column
    quran_df['Sura ID'] = quran_df['Sura Name'].apply(lambda x: sura_id_map[x])
    quran_df['Location'] = quran_df.apply(lambda row: update_location(row, sura_id_map), axis=1)

    # Prepare data for n-gram model
    ngram_data = prepare_ngram_data(quran_df, n=3)

    # Train model
    ngram_model = train_ngram_model(ngram_data)

    # Example prediction
    #input_sequence = ['عملوا', 'يوم', 'القيامة']
    #input_sequence = ["الله", "هم", "المفلحون"]
    input_sequence = quran_df['Token'].tolist()[100:103]
    next_word, location, sura_name = predict_next_word(ngram_model, input_sequence, id_to_sura_name)
    print("Oringinal Sequence:", input_sequence)
    print("Predicted next word:", next_word)
    print("Location:", location)
    print("Sura Name:", sura_name)

Oringinal Sequence: ['أنزلنا', 'آيات', 'بينات']
Predicted next word: وللكافرين
Location: T16A5S58J28N1
Sura Name: المجادلة


In [ ]:
import pandas as pd
import numpy as np
from collections import defaultdict
import random

# Step 1: Load the dataset
def load_data(file_path):
    return pd.read_excel(file_path)

# Step 2: Map Sura names to numerical IDs and create reverse map
def create_sura_id_map(df, sura_col='Sura Name'):
    sura_names = df[sura_col].unique()
    sura_name_to_id = {name: i+1 for i, name in enumerate(sura_names)}
    id_to_sura_name = {i+1: name for i, name in enumerate(sura_names)}
    return sura_name_to_id, id_to_sura_name

# Step 3: Update locations in the dataset
def update_location(row, sura_name_to_id):
    sura_id = sura_name_to_id.get(row['Sura Name'], 0)
    updated_location = f"{row['Location']}N{sura_id}"
    return updated_location

# Step 4: Prepare the dataset for the n-gram model
def prepare_ngram_data(df, n=3):
    # Create tuples of (sequence, next word, location of next word, sura of next word)
    data = []
    tokens = df['Token'].tolist()
    locations = df['Location'].tolist()
    suras = df['Sura Name'].tolist()
    for i in range(len(tokens)-n):
        sequence = tokens[i:i+n]
        next_word = tokens[i+n]
        next_location = locations[i+n]
        next_sura_id = df.loc[i+n, 'Sura ID']  # using Sura ID directly from the dataframe
        data.append((sequence, next_word, next_location, next_sura_id))
    return data

# Step 5: Train an n-gram model with location and sura
def train_ngram_model(data):
    model = defaultdict(lambda: [])
    for sequence, next_word, loc, sura_id in data:
        model[tuple(sequence)].append((next_word, loc, sura_id))
    return model

# Step 6: Prediction function with location and sura name output for a sequence of words
def predict_next_sequence(model, input_sequence, id_to_sura_name, sequence_length=3):
    current_input = input_sequence[-3:]  # start with the last three words
    predicted_sequence = []
    for _ in range(sequence_length):
        current_tuple = tuple(current_input[-3:])  # always use the last three words
        if current_tuple in model:
            predictions = model[current_tuple]
            chosen_prediction = random.choice(predictions)  # Randomly choose among the predictions
            next_word, location, sura_id = chosen_prediction
            sura_name = id_to_sura_name[sura_id]
            predicted_sequence.append((next_word, location, sura_name))
            current_input.append(next_word)  # append the predicted word for the next round
        else:
            predicted_sequence.append(("Word not found", None, None))
            break  # exit if a word is not found
    return predicted_sequence

In [ ]:
# Main execution
if __name__ == "__main__":
    # Load data
    quran_df = load_data('/content/drive/MyDrive/Quran_df.xlsx')

    sura_id_map, id_to_sura_name = create_sura_id_map(quran_df)
    quran_df['Sura ID'] = quran_df['Sura Name'].apply(lambda x: sura_id_map[x])
    quran_df['Location'] = quran_df.apply(lambda row: update_location(row, sura_id_map), axis=1)
    ngram_data = prepare_ngram_data(quran_df, n=3)
    ngram_model = train_ngram_model(ngram_data)

    # Predicting sequence
    #input_sequence = ['عملوا', 'يوم', 'القيامة']
    input_sequence = quran_df['Token'].tolist()[100:103]
    predicted_sequence = predict_next_sequence(ngram_model, input_sequence, id_to_sura_name, sequence_length=3)
    print("Oringinal Sequence:", input_sequence)
    print("Predicted Sequence:", predicted_sequence)

Oringinal Sequence: ['أنزلنا', 'آيات', 'بينات']
Predicted Sequence: [('وللكافرين', 'T16A5S58J28N1', 'المجادلة'), ('عذاب', 'T17A5S58J28N1', 'المجادلة'), ('مهين', 'T18A5S58J28N1', 'المجادلة')]


In [ ]:
def interactive_prediction_app(model, id_to_sura_name, initial_text, sequence_length=3):
    # Split the text by spaces to get the list of tokens
    input_sequence = initial_text.split()

    # Ensure the input is at least 3 words
    if len(input_sequence) < 3:
        return "Input must be at least three words."

    # Predict the next sequence of words
    predicted_sequence = predict_next_sequence(model, input_sequence, id_to_sura_name, sequence_length)

    # Format the output to return only the text
    output_text = ' '.join([word for word, loc, sura in predicted_sequence])
    return output_text

# Example of setting up and using the interactive app
if __name__ == "__main__":
    # Load data, prepare model as before
    quran_df = load_data('/content/drive/MyDrive/Quran_df.xlsx')
    sura_id_map, id_to_sura_name = create_sura_id_map(quran_df)
    quran_df['Sura ID'] = quran_df['Sura Name'].apply(lambda x: sura_id_map[x])
    quran_df['Location'] = quran_df.apply(lambda row: update_location(row, sura_id_map), axis=1)
    ngram_data = prepare_ngram_data(quran_df, n=3)
    ngram_model = train_ngram_model(ngram_data)

    # Interactive prediction
    initial_text = "قد سمع الله قول"
    print("Input text:", initial_text)
    print("Predicted continuation:", interactive_prediction_app(ngram_model, id_to_sura_name, initial_text, sequence_length=3))


Input text: قد سمع الله قول
Predicted continuation: التي تجادلك في


In [ ]:
import pandas as pd
import numpy as np
from collections import defaultdict
import random

# Step 1: Load the dataset
def load_data(file_path):
    return pd.read_excel(file_path)

# Step 2: Map Sura names to numerical IDs and create reverse map
def create_sura_id_map(df, sura_col='Sura Name'):
    sura_names = df[sura_col].unique()
    sura_name_to_id = {name: i+1 for i, name in enumerate(sura_names)}
    id_to_sura_name = {i+1: name for i, name in enumerate(sura_names)}
    return sura_name_to_id, id_to_sura_name

# Step 3: Update locations in the dataset
def update_location(row, sura_name_to_id):
    sura_id = sura_name_to_id.get(row['Sura Name'], 0)
    updated_location = f"{row['Location']}N{sura_id}"
    return updated_location

# Step 4: Prepare the dataset for the n-gram model
def prepare_ngram_data(df, n=3):
    # Create tuples of (sequence, next word, location of next word, sura of next word)
    data = []
    tokens = df['Token'].tolist()
    locations = df['Location'].tolist()
    suras = df['Sura Name'].tolist()
    for i in range(len(tokens)-n):
        sequence = tokens[i:i+n]
        next_word = tokens[i+n]
        next_location = locations[i+n]
        next_sura_id = df.loc[i+n, 'Sura ID']  # using Sura ID directly from the dataframe
        data.append((sequence, next_word, next_location, next_sura_id))
    return data

# Step 5: Train an n-gram model with location and sura
def train_ngram_model(data):
    model = defaultdict(lambda: [])
    for sequence, next_word, loc, sura_id in data:
        model[tuple(sequence)].append((next_word, loc, sura_id))
    return model

# Step 6: Prediction function with location and sura name output for a sequence of words
def predict_next_sequence(model, input_sequence, id_to_sura_name, sequence_length=3):
    current_input = input_sequence[-3:]  # start with the last three words
    predicted_sequence = []
    for _ in range(sequence_length):
        current_tuple = tuple(current_input[-3:])  # always use the last three words
        if current_tuple in model:
            predictions = model[current_tuple]
            chosen_prediction = random.choice(predictions)  # Randomly choose among the predictions
            next_word, location, sura_id = chosen_prediction
            sura_name = id_to_sura_name[sura_id]
            predicted_sequence.append((next_word, location, sura_name))
            current_input.append(next_word)  # append the predicted word for the next round
        else:
            predicted_sequence.append(("You probably made a spelling error", None, None))
            break  # exit if a word is not found
    return predicted_sequence

def interactive_command_line_app(model, id_to_sura_name):
    print("Welcome to the Quranic Text Prediction Tool!")
    print("Type a sequence of three or more words from the Quran and the model will predict the next words.")
    print("Type 'exit' to quit the application.\n")

    while True:
        initial_text = input("Enter your text: ")
        if initial_text.lower() == 'exit':
            print("Exiting the application. Goodbye!")
            break

        # Split the text by spaces to get the list of tokens
        input_sequence = initial_text.split()

        # Ensure the input is at least 3 words
        if len(input_sequence) < 3:
            print("Error: Input must be at least three words long.\n")
            continue

        # Predict the next sequence of words
        predicted_sequence = predict_next_sequence(model, input_sequence, id_to_sura_name, sequence_length=3)

        # Format the output to return only the text (handle custom error message)
        output_text = ' '.join([word for word, loc, sura in predicted_sequence if word != "Check the spelling of your text"])
        if not output_text:
            output_text = "You probably made a spelling error"
        print("Predicted continuation: " + output_text + "\n")


# Main execution for the interactive command line application
if __name__ == "__main__":
    # Load data, prepare model as before
    quran_df = load_data('/content/drive/MyDrive/Quran_df.xlsx')
    sura_id_map, id_to_sura_name = create_sura_id_map(quran_df)
    quran_df['Sura ID'] = quran_df['Sura Name'].apply(lambda x: sura_id_map[x])
    quran_df['Location'] = quran_df.apply(lambda row: update_location(row, sura_id_map), axis=1)
    ngram_data = prepare_ngram_data(quran_df, n=3)
    ngram_model = train_ngram_model(ngram_data)

    # Start the interactive command line application
    interactive_command_line_app(ngram_model, id_to_sura_name)

Welcome to the Quranic Text Prediction Tool!
Type a sequence of three or more words from the Quran and the model will predict the next words.
Type 'exit' to quit the application.

Enter your text: قل اعود برب الناس
Predicted continuation: You probably made a spelling error

Enter your text: قل أعود برب الناس
Predicted continuation: You probably made a spelling error

Enter your text: قل أعوذ برب الناس
Predicted continuation: ملك الناس إله

Enter your text: exit
Exiting the application. Goodbye!


In [ ]:
# Step 4: Prepare the dataset for the n-gram model
def prepare_ngram_data(df, n=3):
    data = []
    tokens = df['Token'].tolist()
    locations = df['Location'].tolist()
    for i in range(len(tokens) - n):
        sequence = tokens[i:i+n]
        next_word = tokens[i+n]
        next_location = locations[i+n]
        data.append((sequence, next_word, next_location))
    return data

df = load_data('/content/drive/MyDrive/Quran_df.xlsx')
data = prepare_ngram_data(df)
print(data)

[(['قد', 'سمع', 'الله'], 'قول', 'T4A1S58J28'), (['سمع', 'الله', 'قول'], 'التي', 'T5A1S58J28'), (['الله', 'قول', 'التي'], 'تجادلك', 'T6A1S58J28'), (['قول', 'التي', 'تجادلك'], 'في', 'T7A1S58J28'), (['التي', 'تجادلك', 'في'], 'زوجها', 'T8A1S58J28'), (['تجادلك', 'في', 'زوجها'], 'وتشتكي', 'T9A1S58J28'), (['في', 'زوجها', 'وتشتكي'], 'إلى', 'T10A1S58J28'), (['زوجها', 'وتشتكي', 'إلى'], 'الله', 'T11A1S58J28'), (['وتشتكي', 'إلى', 'الله'], 'والله', 'T12A1S58J28'), (['إلى', 'الله', 'والله'], 'يسمع', 'T13A1S58J28'), (['الله', 'والله', 'يسمع'], 'تحاوركما', 'T14A1S58J28'), (['والله', 'يسمع', 'تحاوركما'], 'إن', 'T15A1S58J28'), (['يسمع', 'تحاوركما', 'إن'], 'الله', 'T16A1S58J28'), (['تحاوركما', 'إن', 'الله'], 'سميع', 'T17A1S58J28'), (['إن', 'الله', 'سميع'], 'بصير', 'T18A1S58J28'), (['الله', 'سميع', 'بصير'], 'الذين', 'T1A2S58J28'), (['سميع', 'بصير', 'الذين'], 'يظاهرون', 'T2A2S58J28'), (['بصير', 'الذين', 'يظاهرون'], 'منكم', 'T3A2S58J28'), (['الذين', 'يظاهرون', 'منكم'], 'من', 'T4A2S58J28'), (['يظاهرون', 'منك

In [ ]:
import pandas as pd
import numpy as np
from collections import defaultdict
import random

# Step 1: Load the dataset
def load_data(file_path):
    return pd.read_excel(file_path)

# Step 2: Map Sura names to numerical IDs and create reverse map
def create_sura_id_map(df, sura_col='Sura Name', sura_num_col='Sura Number'):
    sura_names = df[sura_col].unique()
    sura_name_to_num = {name: df[df[sura_col] == name][sura_num_col].iloc[0] for name in sura_names}
    num_to_sura_name = {df[df[sura_col] == name][sura_num_col].iloc[0]: name for name in sura_names}
    return sura_name_to_num, num_to_sura_name

# Step 3: Update locations in the dataset
def update_location(row, sura_name_to_id):
    sura_id = sura_name_to_id.get(row['Sura Name'], 0)
    updated_location = f"{row['Location']}N{sura_id}"
    return updated_location

# Step 4: Prepare the dataset for the n-gram model
def prepare_ngram_data(df, n=3):
    data = []
    tokens = df['Token'].tolist()
    locations = df['Location'].tolist()
    for i in range(len(tokens) - n):
        sequence = tokens[i:i+n]
        next_word = tokens[i+n]
        next_location = locations[i+n]
        data.append((sequence, next_word, next_location))
    return data

# Step 5: Train an n-gram model with location and sura
def train_ngram_model(data):
    model = defaultdict(lambda: [])
    for sequence, next_word, location in data:
        model[tuple(sequence)].append((next_word, location))
    return model

def parse_location(location):
    # Example location format: 'T<token>A<ayah>S<sura>J<juz>N<num>'
    try:
        parts = location.split('A')
        ayah_part = parts[1]
        ayah = int(ayah_part.split('S')[0])
        sura = int(ayah_part.split('S')[1].split('J')[0])
        return sura, ayah
    except (IndexError, ValueError) as e:
        print(f"Error parsing location: {location} - {e}")
        return None, None

def predict_next_sequence(model, input_sequence, sequence_length=3):
    current_input = input_sequence[-3:]
    predicted_sequence = []
    sura, ayah = None, None
    for _ in range(sequence_length):
        current_tuple = tuple(current_input[-3:])
        if current_tuple in model:
            predictions = model[current_tuple]
            chosen_prediction = random.choice(predictions)
            next_word, location = chosen_prediction
            sura, ayah = parse_location(location)
            predicted_sequence.append(next_word)
            current_input.append(next_word)
        else:
            predicted_sequence.append("You probably made a spelling error")
            break
    return predicted_sequence, sura, ayah

def interactive_command_line_app(model):
    print("Welcome to the Quranic Text Prediction Tool!")
    print("Type a sequence of three or more words from the Quran and the model will predict the next words.")
    print("Type 'exit' to quit the application.\n")

    while True:
        initial_text = input("Enter your text: ")
        if initial_text.lower() == 'exit':
            print("Exiting the application. Goodbye!")
            break

        input_sequence = initial_text.split()
        if len(input_sequence) < 3:
            print("Error: Input must be at least three words long.\n")
            continue

        predicted_sequence, sura, ayah = predict_next_sequence(model, input_sequence, 3)
        output_text = ' '.join(predicted_sequence)  # since predicted_sequence already contains only words


        if sura and ayah:
            print(f"Predicted continuation: {output_text}")
            print(f"This corresponds to Sura number {sura}, Ayah {ayah}\n")
        else:
            print(output_text + "\n")

# Main execution for the interactive command line application
if __name__ == "__main__":
    quran_df = load_data('/content/drive/MyDrive/Quran_df.xlsx')
    ngram_data = prepare_ngram_data(quran_df, n=3)
    ngram_model = train_ngram_model(ngram_data)

    interactive_command_line_app(ngram_model)

Welcome to the Quranic Text Prediction Tool!
Type a sequence of three or more words from the Quran and the model will predict the next words.
Type 'exit' to quit the application.

Enter your text: قل هو الله أحد
Predicted continuation: الله الصمد لم
This corresponds to Sura number 112, Ayah 3

Enter your text: exit
Exiting the application. Goodbye!


In [ ]:
import pandas as pd
import numpy as np
from collections import defaultdict
import random

# Load the dataset
def load_data(file_path):
    return pd.read_excel(file_path)

def parse_location(location):
    try:
        token_part, ayah_part, sura_part = location.split('A')[0], location.split('A')[1].split('S')[0], location.split('S')[1].split('J')[0]
        ayah = int(ayah_part)
        sura = int(sura_part)
        return sura, ayah
    except (IndexError, ValueError) as e:
        print(f"Error parsing location: {location} - {e}")
        return None, None

def create_sura_id_map(df):
    sura_names = df['Sura Name'].unique()
    num_to_sura_name = {}
    for name in sura_names:
        sample_location = df[df['Sura Name'] == name]['Location'].iloc[0]
        sura_number, _ = parse_location(sample_location)
        num_to_sura_name[sura_number] = name
        #print(f"Location: {sample_location}, Extracted Sura: {sura_number}, Name: {name}")  # Debugging line
    return num_to_sura_name

def prepare_ngram_data(df, n=3):
    data = []
    tokens = df['Token'].tolist()
    locations = df['Location'].tolist()
    for i in range(len(tokens) - n):
        sequence = tokens[i:i+n]
        next_word = tokens[i+n]
        next_location = locations[i+n]
        data.append((sequence, next_word, next_location))
    return data

def train_ngram_model(data):
    model = defaultdict(lambda: [])
    for sequence, next_word, location in data:
        model[tuple(sequence)].append((next_word, location))
    return model

def predict_next_sequence(model, input_sequence, sequence_length=3):
    current_input = input_sequence[-3:]  # use the last three words
    predicted_sequence = []
    sura, ayah = None, None
    for _ in range(sequence_length):
        current_tuple = tuple(current_input[-3:])
        if current_tuple in model:
            predictions = model[current_tuple]
            chosen_prediction = random.choice(predictions)
            next_word, location = chosen_prediction
            sura, ayah = parse_location(location)
            predicted_sequence.append(next_word)
            current_input.append(next_word)
        else:
            predicted_sequence.append("You probably made a spelling error")
            break
    return predicted_sequence, sura, ayah

def interactive_command_line_app(model, num_to_sura_name):
    print("Welcome to the Quranic Text Prediction Tool!")
    print("Type a sequence of three or more words from the Quran and the model will predict the next words.")
    print("Type 'exit' to quit the application.\n")

    while True:
        initial_text = input("Enter your text: ")
        if initial_text.lower() == 'exit':
            print("Exiting the application. Goodbye!")
            break

        input_sequence = initial_text.split()
        if len(input_sequence) < 4:
            print("Error: Input must be at least three words long.\n")
            continue

        predicted_sequence, sura, ayah = predict_next_sequence(model, input_sequence, 3)
        output_text = ' '.join(predicted_sequence)

        if sura and ayah:
            sura_name = num_to_sura_name.get(sura, f"Unknown Sura for ID {sura}")
            print(f"Predicted continuation: {output_text}")
            print(f"This corresponds to Sura: {sura_name} (Sura number {sura}), Ayah {ayah}\n")
        else:
            print(output_text + "\n")


if __name__ == "__main__":
    quran_df = load_data('/content/drive/MyDrive/Quran_df.xlsx')

    # Create sura to ID map and extract data for n-gram model training
    num_to_sura_name = create_sura_id_map(quran_df)  # This function should now work correctly
    ngram_data = prepare_ngram_data(quran_df, n=4)
    ngram_model = train_ngram_model(ngram_data)

    # Start the interactive command line application with the correct Sura names
    interactive_command_line_app(ngram_model, num_to_sura_name)


Welcome to the Quranic Text Prediction Tool!
Type a sequence of three or more words from the Quran and the model will predict the next words.
Type 'exit' to quit the application.

Enter your text: قل هو الله احد
You probably made a spelling error

Enter your text: exit
Exiting the application. Goodbye!
